version : '3.1'
services:
    aplicationjava:
      container_name: tomcat
      image: automcat
      ports:
        - 8081:8080
      restart: always
      volumes:
        - ./sample.war:/usr/local/webapps/sample.war
        
    proxy:
      container_name: nginx
      image: nginx
      ports:
        - 8080:8080
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
        
       
